### PR TITLE
[MRG] CDNs, slice view, updated pipeline

### LINKED ISSUE #19: Improve web visualization to show FreeSurfer meshes
#### Describe the problem
New webviz stuff will allow the user to load up a Freesurfer-processed (mgz/nifti) file alongside the Freesurfer meshes to view both in the same space. You can toggle the electrodes/meshes to get a better idea of the anatomy.

#### Describe your solution
An improvement in the input data files of `neuroimg/pipeline/visualization`

### PR DESCRIPTION
**Pull request by TheBrainChain**
Closes: #19 

I've included the 'registration_pipeline' folder that is my pipeline that you adapted previously into snakemake format (it would basically replace the current 'scripts' folder).  
It includes the elec2vox.sh script to extract the anatomical locations of the electrodes.

Additionally the new webviz stuff will allow the user to load up a Freesurfer-processed (mgz/nifti) file alongside the Freesurfer meshes to view both in the same space. You can toggle the electrodes/meshes to get a better idea of the anatomy.

- [ ] Adapt new registration_pipeline to snakemake format
- [ ] Add additional rule to output anatomical location file

### CODE REVIEW

**Review by adam2392 — CHANGES_REQUESTED** [review]
Hi @TheBrainChain thanks for this. I was thinking that it might be easier maintainability if we separate out the pipelines as much as possible, so each can be debugged, or maintained independently. Currently, in `neuroimg/pipeline`, there are the following pipelines:

1. reconstruction: FreeSurfer and various derivatives (to be BIDS compatible)
2. coregistration: FSL coregistration and anything that involves getting images from one space to another. Here it'll depend on reconstruction, so we can map the corresponding brain masks and such into CT space, and then mapping CT -> MRI space.
2. contact_localization:  semi-automated localization w/ @ChesterHuynh 's algorithm, and then mapping these into files (hopefully BIDS compatible)
3. postprocessing: any sort of niceties of converting data into the correct format, so we don't have to worry about differing formats throughout pipelines. We might be able to axe this, if we stick w/ BIDS strong enough.
4. visualization: runs things that pull data from the previous pipelines to show the stuff you've been working on.

What do you think of that current organization and if it makes sense?

**Comment by adam2392** [comment]
Regarding actual PR, just a few questions regarding code and layout:

Are these files necessarily needed? 
1. neuroimg/pipeline/visualization/registration_pipeline/pipeline.sh: seems like it'll just run a pipeline using post-Freesurfer data right? We can add this into a specific pipeline with other post-processing data to make it cleaner. Lmk what you think.
2. neuroimg/pipeline/visualization/registration_pipeline/recon.sh: more or less running Freesurfer right? Is there a difference to `neuroimg/pipeline/reconstruction/`?

Can we delete these files, or incorporate into an existing `neuroimg/pipeline`?
1. `neuroimg/pipeline/visualization/registration_pipeline/scripts/reconall.sh`
2. any other scripts dealing w/ FreeSurfer, or FSL?

Is `neuroimg/pipeline/visualization/registration_pipeline/scripts/aseg2srf.sh` different from the aseg2srf in `neuroimg/format/aseg2srf.sh`?

What is `neuroimg/pipeline/visualization/registration_pipeline/scripts/elec2vox.sh` trying to do? Map electrode coordinates to voxels?

**Comment by TheBrainChain** [comment]
So 90% of the registration_pipeline (my original pipeline) folder can most likely be removed. There are a few adaptations that need to be made to the aseg2srf script (that the reconstruction pipeline references) to incorporate additional labels. I can prune that with the next update.
I believe you incorporated most of the pipeline.sh into the Snakefile, and the reconall.sh can be discarded.
elec2vox.sh takes in an .txt file that has electrode labels/Cartesian coordinates in T1-space and generates the corresponding labels in the aseg+aparc/FreesurferLUT. I'll need to adapt that to fit @ChesterHuynh's output format.

**Comment by adam2392** [comment]
Gonna merge these in and then remove the unnecessary files.

**Pull request merged**
